language: generic
env:
  global:
    - IDE_VERSION=1.8.13
  matrix:
    - BOARD="espressif:esp32:esp32:FlashFreq=80"

before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "esp8266:esp8266:" ]]; then
      arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --install-boards esp8266:esp8266;
      arduino --pref "boardsmanager.additional.urls=" --save-prefs;
    fi
  - if [[ "$BOARD" =~ "espressif:esp32:" ]]; then
      mkdir -p ~/Arduino/hardware/espressif &&
      cd ~/Arduino/hardware/espressif &&
      git clone https://github.com/espressif/arduino-esp32.git esp32 &&
      cd esp32/tools/ &&
      python get.py &&
      cd $TRAVIS_BUILD_DIR;
    fi
  - arduino --install-library HX711 Arduino Library
  - arduino --install-library DHT sensor library
  - buildExampleSketch() { arduino --verbose-build --verify --board $BOARD $PWD/examples/$1/$1.ino; }
  - buildSketch() { arduino --verbose-build --verify --board $BOARD $PWD/$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/ArduinoUniqueID
script:
  - buildSketch esp32-google-sheet